---
- name: Init host for management
  hosts: "{{ workspace }}"
  become: yes
  gather_facts: yes
  tags:
    - system

  roles:
    - role: "system_base"
    - role: "system_users"
    - role: "dns"
    - role: "mailserver"
    - role: "container"
    - role: "monitor"